// <auto-generated />
using System;
using Gantt_Chart_Backend.Data.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gantt_Chart_Backend.Migrations
{
    [DbContext(typeof(GanttPlatformDbContext))]
    [Migration("20251208151909_Many-Many-Performers")]
    partial class ManyManyPerformers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("AuthorId", "AuthorProjectId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.Dependence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentId");

                    b.ToTable("dependence", (string)null);
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.InviteCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.ToTable("InviteCodes");
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("permission", (string)null);
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RootTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("RootTaskId")
                        .IsUnique();

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_member", (string)null);
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("task", (string)null);
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeaderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("LeaderId", "ProjectId");

                    b.ToTable("team", (string)null);
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("PermissionProjectMember", b =>
                {
                    b.Property<Guid>("PermissionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectMemberProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("PermissionsId", "ProjectMemberId", "ProjectMemberProjectId");

                    b.HasIndex("ProjectMemberId", "ProjectMemberProjectId");

                    b.ToTable("PermissionProjectMember");
                });

            modelBuilder.Entity("ProjectMemberTeam", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PerformersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PerformersProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamId", "PerformersId", "PerformersProjectId");

                    b.HasIndex("PerformersId", "PerformersProjectId");

                    b.ToTable("ProjectMemberTeam");
                });

            modelBuilder.Entity("task_performers_teams", b =>
                {
                    b.Property<Guid>("task_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("team_id")
                        .HasColumnType("uuid");

                    b.HasKey("task_id", "team_id");

                    b.HasIndex("team_id");

                    b.ToTable("task_performers_teams", (string)null);
                });

            modelBuilder.Entity("task_performers_users", b =>
                {
                    b.Property<Guid>("task_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("project_member_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("project_id")
                        .HasColumnType("uuid");

                    b.HasKey("task_id", "project_member_id", "project_id");

                    b.HasIndex("project_member_id", "project_id");

                    b.ToTable("task_performers", (string)null);
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.Comment", b =>
                {
                    b.HasOne("Gantt_Chart_Backend.Data.Models.ProjectTask", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gantt_Chart_Backend.Data.Models.ProjectMember", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId", "AuthorProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.Dependence", b =>
                {
                    b.HasOne("Gantt_Chart_Backend.Data.Models.ProjectTask", "ChildTask")
                        .WithMany("Dependencies")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gantt_Chart_Backend.Data.Models.ProjectTask", "ParentTask")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildTask");

                    b.Navigation("ParentTask");
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.InviteCode", b =>
                {
                    b.HasOne("Gantt_Chart_Backend.Data.Models.Project", "Project")
                        .WithMany("InviteCodes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.Project", b =>
                {
                    b.HasOne("Gantt_Chart_Backend.Data.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gantt_Chart_Backend.Data.Models.ProjectTask", "RootTask")
                        .WithOne()
                        .HasForeignKey("Gantt_Chart_Backend.Data.Models.Project", "RootTaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Creator");

                    b.Navigation("RootTask");
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.ProjectMember", b =>
                {
                    b.HasOne("Gantt_Chart_Backend.Data.Models.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gantt_Chart_Backend.Data.Models.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.ProjectTask", b =>
                {
                    b.HasOne("Gantt_Chart_Backend.Data.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.Team", b =>
                {
                    b.HasOne("Gantt_Chart_Backend.Data.Models.Project", "Project")
                        .WithMany("Teams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gantt_Chart_Backend.Data.Models.ProjectMember", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Leader");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PermissionProjectMember", b =>
                {
                    b.HasOne("Gantt_Chart_Backend.Data.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gantt_Chart_Backend.Data.Models.ProjectMember", null)
                        .WithMany()
                        .HasForeignKey("ProjectMemberId", "ProjectMemberProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectMemberTeam", b =>
                {
                    b.HasOne("Gantt_Chart_Backend.Data.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gantt_Chart_Backend.Data.Models.ProjectMember", null)
                        .WithMany()
                        .HasForeignKey("PerformersId", "PerformersProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("task_performers_teams", b =>
                {
                    b.HasOne("Gantt_Chart_Backend.Data.Models.ProjectTask", null)
                        .WithMany()
                        .HasForeignKey("task_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gantt_Chart_Backend.Data.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("team_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("task_performers_users", b =>
                {
                    b.HasOne("Gantt_Chart_Backend.Data.Models.ProjectTask", null)
                        .WithMany()
                        .HasForeignKey("task_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gantt_Chart_Backend.Data.Models.ProjectMember", null)
                        .WithMany()
                        .HasForeignKey("project_member_id", "project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.Project", b =>
                {
                    b.Navigation("InviteCodes");

                    b.Navigation("Members");

                    b.Navigation("Tasks");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.ProjectTask", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("Gantt_Chart_Backend.Data.Models.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
