stages:
  - build
  - deploy

build_job:
  stage: build
  tags:
    - bellinghem
  script:
    - echo "Фиксаируем версии инструментов сборки"
    - docker version > versions.txt
    - docker compose version > versions.txt
  artifacts:
    paths:
      - versions.txt
      - expire_in: 1 day


deploy_job:
  stage: deploy 
  tags:
    - bellinghem
  script:
    - echo "Помчали деплой..."
    - docker compose up -d --build
    - echo "Список запущенных контейнеров:"
    - docker ps > deploy_data.txt
  artifacts:
    paths:
      - deploy_data.txt
    when: always
