stages:
  - build
  - test
  - deploy
  - notification

.base_template:
  tags:
    - bellinghem
  interruptible: true
  retry:
    max: 2
    when: runner_system_failure

cache:
  key: "$CI_COMMIT_REF_SLUG" 
  paths:
    - frontend/node_modules/
    - backend/obj/         
    - backend/bin/
    - .npm/ 

build_job:
  extends: .base_template
  stage: build
  script:
    - echo "Фиксаируем версии инструментов сборки"
    - docker version > versions.txt
    - docker compose version >> versions.txt
  artifacts:
    paths:
      - versions.txt
    expire_in: 1 day

lint_job:
  extends: .base_template
  stage: test
  script:
    - echo "Запускаем проверку кода"
    - sleep 5
    - echo "Код в порядке"

deploy_job:
  extends: .base_template
  stage: deploy 
  needs:
    - job: build_jobbbb
    - job: lint_job
  environment:
    name: production 
    url: http://158.160.8.109
  script:
    - echo "Помчали деплой..."
    - docker compose up -d --build
    - echo "Список запущенных контейнеров:"
    - echo "Деплой производится на сервер -  $SERVER_IP"
    - echo "Проверка наличия пароля БД - $DB_PASSWORD"
    - docker ps > deploy_data.txt
  artifacts:
    paths:
      - deploy_data.txt
    when: always




message_good:
  extends: .base_template
  stage: notification 
  rules:
    - when: on_success
  script:
    - |
      MSG="*АААААААА* Пайплайн проекта ${CI_PROJECT_NAME}успеХ. %0A Статус: ${CI_JOB_STATUS} %0A Версия: ${CI_COMMIT_SHORT_SHA}"
      curl --fail -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
        -d "chat_id=${TELEGRAM_CHAT_ID}" \
        -d "parse_mode=Markdown" \
        -d "text=${MSG}"

message_bad:
  extends: .base_template
  stage: notification
  rules:
    - when: on_failure 
  script:
    - |
      MSG="*охХХХХХХ* Пайплайн проекта ${CI_PROJECT_NAME} УПАД. %0A Статус: failure %0A [Логи](${CI_PIPELINE_URL})"
      curl --fail -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
        -d "chat_id=${TELEGRAM_CHAT_ID}" \
        -d "parse_mode=Markdown" \
        -d "text=${MSG}"